#!/usr/bin/env bash
set -euo pipefail

DEVICECOUNT=$(echo "$(adb devices | wc -l) - 2" | bc)

if [[ "$DEVICECOUNT" -eq 0 ]]
then
    echo "No ADB devices connected."
    exit 1
fi

if [[ "$DEVICECOUNT" -gt 1 ]]
then
    SERIAL=$(adb devices -l | sed '1d' | head -n -1 \
    | fzf --reverse --prompt "Select device: " --height=5 \
    | cut -f 1 -d ' ' \
    )
else
    SERIAL=$(adb devices -l | sed '1d' | head -n -1 | cut -f 1 -d ' ')
fi

PACKAGES=$(adb -s "$SERIAL" shell pm list packages -3 | cut -d ':' -f 2 | sort \
    | fzf --reverse --multi \
    --preview-window right:40% \
    --preview "echo {} | xargs -I % curl -s -o- \"https://play.google.com/store/apps/details?id=%\" |  grep -oh '<title id=\"main-title\">.*</title>'  | cut -d '>' -f 2 | cut -d '<' -f 1 | rev | cut -d '-' -f2- | rev" \
)

if [[ ! -z "$PACKAGES" ]]; then
    PACKAGES_LIST=$(echo "$PACKAGES" | tr ' ' '\n')
    echo "Selected packages ($(echo "${PACKAGES_LIST}" | wc -l)):"
    echo "$PACKAGES"
    read -r -p "Confirm uninstall? [Y/n]" response
    response=$(echo "$response" | tr '[:upper:]' '[:lower:]') # tolower
    if [[ "$response" =~ ^(yes|y| ) ]] || [ -z "$response" ]; then
        echo "$PACKAGES" | xargs -I % adb -s "$SERIAL"  shell pm uninstall "%"
    fi
else
    echo "No packages selected"
fi