#!/usr/bin/env bash
set -euo pipefail

DEVICECOUNT=$(echo "$(adb devices | wc -l) - 2" | bc)


function parse_response(){
    local response=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    if [[ "$response" =~ ^(yes|y| ) ]] || [ -z "$response" ]; then
        echo 0
    else
        echo 1
    fi
}

if [[ "$DEVICECOUNT" -eq 0 ]]
then
    echo "No ADB devices connected."
    exit 1
fi

if [[ "$DEVICECOUNT" -gt 1 ]]
then
    SERIAL=$(adb devices -l | sed '1d' | head -n -1 \
    | fzf --reverse --prompt "Select device: " --height=5 \
    | cut -f 1 -d ' ' \
    )
else
    SERIAL=$(adb devices -l | sed '1d' | head -n -1 | cut -f 1 -d ' ')
fi

PACKAGES=$(adb -s "$SERIAL" shell pm list packages -3 | cut -d ':' -f 2 | sort \
    | fzf --reverse --multi \
    --preview-window right:40% \
    --preview "echo {} | xargs -I % curl -s -o- \"https://play.google.com/store/apps/details?id=%\" |  grep -oh '<title id=\"main-title\">.*</title>'  | cut -d '>' -f 2 | cut -d '<' -f 1 | rev | cut -d '-' -f2- | rev" \
)

if [[ ! -z "$PACKAGES" ]]; then
    PACKAGES_LIST=$(echo "$PACKAGES" | tr ' ' '\n')
    echo "Selected packages ($(echo "${PACKAGES_LIST}" | wc -l)):"
    echo "$PACKAGES"
    read -r -p "Confirm uninstall? [Y/n]" response
    if [[ $(parse_response response) -eq 0 ]]; then
        for package in $PACKAGES_LIST
        do
            echo -n "$package - "
            adb -s "$SERIAL" shell pm uninstall "$package"
            if [ $? -ne 0 ]; then
                read -r -p "Uninstallation failed. Try to uninstall as the android user? [Y/n]" response
                if [[ $(parse_response response) -eq 0 ]]; then
                    adb -s "$SERIAL"  shell pm uninstall --user 0 "$package"
                fi
            fi
        done
    fi
else
    echo "No packages selected"
fi
